Repository VictorPrudente/EduMatch, pull requests merged in 2024-02, with the labels that each got.

#123 Refatoração atendendo critério do JPA
  src/main/java/VS13/Squad09/EduMatch/entities/Contato.java
  src/main/java/VS13/Squad09/EduMatch/repositories/ContatoRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/ContatoService.java
Labels: refactoring

#124 Refatorando classes usuario para JPA
  src/main/java/VS13/Squad09/EduMatch/controllers/UsuarioController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IUsuarioController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/ContatoRelatorioDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/EnderecoRelatorioDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/UsuarioCompletoRelatorioDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Usuario.java
  src/main/java/VS13/Squad09/EduMatch/repositories/UsuarioRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/EmailService.java
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
Labels: documentation, refactoring

#125 Spring/prova
  bd/bd.sql
  src/main/java/VS13/Squad09/EduMatch/controllers/ProvaController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IProvaController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/QuestaoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/prova/ProvaFinishCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/prova/ProvaStartCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/QuestaoDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/prova/ProvaFinishDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/prova/ProvaStartDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Opcao.java
  src/main/java/VS13/Squad09/EduMatch/entities/Prova.java
  src/main/java/VS13/Squad09/EduMatch/entities/Questao.java
  src/main/java/VS13/Squad09/EduMatch/entities/Resposta.java
  src/main/java/VS13/Squad09/EduMatch/entities/Usuario.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/Dificuldade.java
  src/main/java/VS13/Squad09/EduMatch/repositories/ProvaRepository.java
  src/main/java/VS13/Squad09/EduMatch/repositories/QuestaoRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/ProvaService.java
  src/main/java/VS13/Squad09/EduMatch/services/QuestaoService.java
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#128 Spring/insignia
  bd/bd.sql
  src/main/java/VS13/Squad09/EduMatch/controllers/DistintivoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/RankingController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/UsuarioController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IRankingController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IUsuarioController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/QuestaoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/UsuarioCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/QuestaoDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/UsuarioDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Colecionavel.java
  src/main/java/VS13/Squad09/EduMatch/entities/Distintivo.java
  src/main/java/VS13/Squad09/EduMatch/entities/Insignia.java
  src/main/java/VS13/Squad09/EduMatch/entities/Questao.java
  src/main/java/VS13/Squad09/EduMatch/entities/Ranking.java
  src/main/java/VS13/Squad09/EduMatch/entities/Usuario.java
  src/main/java/VS13/Squad09/EduMatch/repositories/DistintivoRepository.java
  src/main/java/VS13/Squad09/EduMatch/repositories/ProvaRepository.java
  src/main/java/VS13/Squad09/EduMatch/repositories/RankingRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/DistintivoService.java
  src/main/java/VS13/Squad09/EduMatch/services/ProvaService.java
  src/main/java/VS13/Squad09/EduMatch/services/RankingService.java
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
Labels: enhancement, bugfix, refactoring

#129 Spring/ranking
  bd/bd.sql
  bd/dados.sql
  src/main/java/VS13/Squad09/EduMatch/controllers/ProvaController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/RankingController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IRankingController.java
  src/main/java/VS13/Squad09/EduMatch/entities/Prova.java
  src/main/java/VS13/Squad09/EduMatch/services/ProvaService.java
  src/main/java/VS13/Squad09/EduMatch/services/RankingService.java
Labels: documentation, enhancement, bugfix, refactoring

#131 fix: correcao de bugs na utilizacao de contato e endereco
  src/main/java/VS13/Squad09/EduMatch/controllers/ContatoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/EnderecoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IContatoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IEnderecoController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/mapper/ContatoMapper.java
  src/main/java/VS13/Squad09/EduMatch/dtos/mapper/EnderecoMapper.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/EnderecoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Contato.java
  src/main/java/VS13/Squad09/EduMatch/entities/Endereco.java
  src/main/java/VS13/Squad09/EduMatch/repositories/ContatoRepository.java
  src/main/java/VS13/Squad09/EduMatch/repositories/EnderecoRepository.java
  src/main/java/VS13/Squad09/EduMatch/repositories/UsuarioRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/ContatoService.java
  src/main/java/VS13/Squad09/EduMatch/services/EnderecoService.java
Labels: bugfix

#132 Spring/usuario
  src/main/java/VS13/Squad09/EduMatch/dtos/request/UsuarioCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/UsuarioDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Certificado.java
  src/main/java/VS13/Squad09/EduMatch/repositories/UsuarioRepository.java
Labels: bug, bugfix

#133 Spring/fix
  bd/bd.sql
  bd/dados.sql
  src/main/java/VS13/Squad09/EduMatch/dtos/request/UsuarioCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/UsuarioDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Usuario.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/TipoUsuario.java
  src/main/java/VS13/Squad09/EduMatch/services/RankingService.java
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
Labels: enhancement, bugfix

#136 feat: security usuario
  bd/bd.sql
  pom.xml
  src/main/java/VS13/Squad09/EduMatch/config/OpenApiConfig.java
  src/main/java/VS13/Squad09/EduMatch/controllers/AuthController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/LoginDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/UsuarioCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Usuario.java
  src/main/java/VS13/Squad09/EduMatch/repositories/UsuarioRepository.java
  src/main/java/VS13/Squad09/EduMatch/security/SecurityConfiguration.java
  src/main/java/VS13/Squad09/EduMatch/security/TokenAuthenticationFilter.java
  src/main/java/VS13/Squad09/EduMatch/security/TokenService.java
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
Labels: documentation

#137 Refatoração de insignia
  EduMatch/bd/bd.sql
  bd/bd.sql
  src/main/java/VS13/Squad09/EduMatch/controllers/InsigniaController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IInsigniasController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/insignia/request/InsigniaCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/insignia/response/InsigniaDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/insignia/response/InsigniaDetailedDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/InsigniaCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/InsigniaDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/UsuarioDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Insignia.java
  src/main/java/VS13/Squad09/EduMatch/entities/Usuario.java
  src/main/java/VS13/Squad09/EduMatch/repositories/InsigniaRepository.java
  src/main/java/VS13/Squad09/EduMatch/security/SecurityConfiguration.java
  src/main/java/VS13/Squad09/EduMatch/services/InsigniaService.java
  src/main/java/VS13/Squad09/EduMatch/services/ProvaService.java
  src/main/resources/application.properties
  src/main/resources/images/RUBY ranking.png
  src/main/resources/images/aluno grao mestre.png
  src/main/resources/images/aluno mestre.png
  src/main/resources/images/ametista ranking.png
  src/main/resources/images/atualidades_dificil.png
  src/main/resources/images/atualidades_facil.png
  src/main/resources/images/atualidades_medio.png
  src/main/resources/images/biologia_dificil.png
  src/main/resources/images/biologia_facil.png
  src/main/resources/images/biologia_medio.png
  src/main/resources/images/bronze icon.png
  src/main/resources/images/diamante ranking.png
  src/main/resources/images/espanhol_dificil.png
  src/main/resources/images/espanhol_facil.png
  src/main/resources/images/espanhol_medio.png
  src/main/resources/images/fisica_dificil.png
  src/main/resources/images/fisica_facil.png
  src/main/resources/images/fisica_medio.png
  src/main/resources/images/geografia_dificil.png
  src/main/resources/images/geografia_facil.png
  src/main/resources/images/geografia_medio.png
  src/main/resources/images/gold ranking.png
  src/main/resources/images/historia_dificil.png
  src/main/resources/images/historia_facil.png
  src/main/resources/images/historia_medio.png
  src/main/resources/images/ingles__facil.png
  src/main/resources/images/ingles_dificil.png
  src/main/resources/images/ingles_medio.png
  src/main/resources/images/iron ranking.png
  src/main/resources/images/master mind.png
  src/main/resources/images/matematica_dificil.png
  src/main/resources/images/matematica_facil.png
  src/main/resources/images/matematica_medio.png
  src/main/resources/images/portugues_dificil.png
  src/main/resources/images/portugues_facil.png
  src/main/resources/images/portugues_medio.png
  src/main/resources/images/quimica_dificil.png
  src/main/resources/images/quimica_facil.png
  src/main/resources/images/quimica_medio.png
  src/main/resources/images/silver ranking.png
  src/main/resources/images/soft_skills_dificil.png
  src/main/resources/images/soft_skills_facil.png
  src/main/resources/images/soft_skills_medio.png
Labels: bug, documentation, enhancement, refactoring

#139 Refatoração Ranking
  bd/bd.sql
  src/main/java/VS13/Squad09/EduMatch/controllers/RankingController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IRankingController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/ranking/request/RankingCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/ranking/response/RankingDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/ranking/response/RankingUsuarioDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/ClassificacaoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Ranking.java
  src/main/java/VS13/Squad09/EduMatch/entities/Usuario.java
  src/main/java/VS13/Squad09/EduMatch/repositories/RankingRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/RankingService.java
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
Labels: documentation, enhancement, bugfix, refactoring

#144 Refatoração Questão e Prova
  bd/bd.sql
  bd/dados.sql
  src/main/java/VS13/Squad09/EduMatch/controllers/ProvaController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/QuestaoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IQuestaoController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/DistintivoDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/UsuarioDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/prova/ProvaFinishDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/usuario/response/EmpresaDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Prova.java
  src/main/java/VS13/Squad09/EduMatch/entities/Questao.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/Dificuldade.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/Elo.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/Resultado.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/Role.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/Status.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/TipoDeContato.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/TipoDeEndereco.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/TipoDistintivo.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/TipoEmpresa.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/TipoUsuario.java
  src/main/java/VS13/Squad09/EduMatch/entities/enums/Trilha.java
  src/main/java/VS13/Squad09/EduMatch/repositories/QuestaoRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/ProvaService.java
  src/main/java/VS13/Squad09/EduMatch/services/QuestaoService.java
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
Labels: bug, documentation, enhancement, refactoring

#153 Refact certificado & Test CertificadoService
  src/main/java/VS13/Squad09/EduMatch/controllers/CertificadoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/ICertificadoController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/CertificadoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Certificado.java
  src/main/java/VS13/Squad09/EduMatch/repositories/CertificadoRepository.java
  src/main/java/VS13/Squad09/EduMatch/security/SecurityConfiguration.java
  src/main/java/VS13/Squad09/EduMatch/services/CertificadoService.java
  src/test/java/VS13/Squad09/EduMatch/services/CertificadoServiceTest.java
Labels: enhancement, refactoring

#154 tests usuario
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
  src/test/java/VS13/Squad09/EduMatch/services/UsuarioServiceTest.java
Labels: enhancement, refactoring

#155 Testes
  src/main/java/VS13/Squad09/EduMatch/controllers/AchievmentsController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/InsigniaController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/RankingController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IInsigniasController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IRankingController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/RankingCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/QuestaoDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Insignia.java
  src/main/java/VS13/Squad09/EduMatch/entities/Ranking.java
  src/main/java/VS13/Squad09/EduMatch/repositories/InsigniaRepository.java
  src/main/java/VS13/Squad09/EduMatch/repositories/RankingRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/InsigniaService.java
  src/main/java/VS13/Squad09/EduMatch/services/ProvaService.java
  src/main/java/VS13/Squad09/EduMatch/services/QuestaoService.java
  src/main/java/VS13/Squad09/EduMatch/services/RankingService.java
  src/main/resources/application.properties
  src/test/java/VS13/Squad09/EduMatch/EduMatchApplicationTests.java
  src/test/java/VS13/Squad09/EduMatch/InsigniaServiceTest.java
  src/test/java/VS13/Squad09/EduMatch/ProvaServiceTest.java
  src/test/java/VS13/Squad09/EduMatch/QuestaoServiceTest.java
  src/test/java/VS13/Squad09/EduMatch/RankingServiceTest.java
Labels: enhancement, refactoring
