Repository VictorPrudente/EduMatch, pull requests merged in 2024-01, with the labels that each got.

#116 add: insignia
  src/main/java/VS13/Squad09/EduMatch/controllers/InsigniaController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/InsigniaCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/InsigniaDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Classificacao.java
  src/main/java/VS13/Squad09/EduMatch/entities/Insignia.java
  src/main/java/VS13/Squad09/EduMatch/repositories/InsigniaRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/InsigniaService.java
Labels: enhancement

#115 Spring/email
  src/main/java/VS13/Squad09/EduMatch/controllers/CertificadoController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/UsuarioCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/services/EmailService.java
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
  src/main/resources/application.properties
Labels: enhancement, refactoring

#117 refact: templates emails
  src/main/resources/templates/email-atualizar-usuario-template.ftl
  src/main/resources/templates/email-criar-usuario-template.ftl
  src/main/resources/templates/email-deletar-usuario-template.ftl
Labels: refactoring

#118 Add: documentação, refact: atualizar e listar por email
  src/main/java/VS13/Squad09/EduMatch/controllers/EmpresaController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/UsuarioController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IEmpresaController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IUsuarioController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/CertificadoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/ContatoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/LoginCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/QuestaoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/UsuarioCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/repositories/UsuarioRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/UsuarioService.java
Labels: documentation, refactoring

#119 Add: documentação
  src/main/java/VS13/Squad09/EduMatch/controllers/ClassificacaoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/InsigniaController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/ICertificadoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IClassificacaoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IContatoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IEmpresaController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IEnderecoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IInsigniasController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IQuestaoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IUsuarioController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/CertificadoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/ClassificacaoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/InsigniaCreateDTO.java
Labels: documentation

#121 Spring/endereco
  EduMatch/bd/bd.sql
  src/main/java/VS13/Squad09/EduMatch/controllers/ContatoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/EnderecoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IContatoController.java
  src/main/java/VS13/Squad09/EduMatch/controllers/interfaces/IEnderecoController.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/ContatoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/request/EnderecoCreateDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/ContatoDTO.java
  src/main/java/VS13/Squad09/EduMatch/dtos/response/EnderecoDTO.java
  src/main/java/VS13/Squad09/EduMatch/entities/Endereco.java
  src/main/java/VS13/Squad09/EduMatch/repositories/ContatoRepository.java
  src/main/java/VS13/Squad09/EduMatch/repositories/EnderecoRepository.java
  src/main/java/VS13/Squad09/EduMatch/services/ContatoService.java
  src/main/java/VS13/Squad09/EduMatch/services/EnderecoService.java
Labels: enhancement, bugfix
